### ISSUE TITLE
Marker on multiple dates

### ISSUE THREAD

**Issue by MuhammadMussadiq** [edwardfxiao/react-picky-date-time#12]
Hello,
Is it possible to add marker on multiple dates?
![image](https://user-images.githubusercontent.com/16952510/137766206-1bb8a682-960c-4369-a2a6-5ac5a151dac9.png)

**Comment by edwardfhsiao** [comment]
Something like <... markedDate={['2021-01-01', '2021-01-02',]} .../> and then these two dates get marked on the chart?

**Comment by edwardfhsiao** [comment]
@MuhammadMussadiq Hi, try v1.7.0
```js
<PickyDateTime
  ...
  markedDates={['10/19/2021']} // OPTIONAL. format: "MM/DD/YYYY"
  ...
/>
```

**Comment by edwardfhsiao** [comment]
@MuhammadMussadiq make sure you pass 01 instead of 1, 
```js
`${month.padStart(2, '0')}/${date.padStart(2, '0')}/${year}`
```

**Comment by MuhammadMussadiq** [comment]
@edwardfhsiao Now, I am able to see the marker on dates. Below are the issues i found

1. Markers will only be shown if the markedDates array size is more than 1. For example if the markedDates size is 1, marker will not be rendered.
` <PickyDateTime  size="s"  mode={1}  show={true} markedDates={[ `10/02/2021`, ]} />`
2. This marker functionality is only available for mode 1 not for mode 0.

I will appreciate if you can fix above issues.

**Comment by edwardfhsiao** [comment]
@MuhammadMussadiq Sorry, that is my bad, gonna fix them in a minute
