### ISSUE TITLE
Great work edward

### ISSUE THREAD

**Issue by koladei** [edwardfxiao/react-picky-date-time#13]
Is it possible to specify minimum and maximum selectable date? If yes, how can I do that?

**Comment by edwardfxiao** [comment]
@koladei Hi, give v1.8.0 a try

just add
```js
<
...
supportDateRange={[`12/03/2021`, `12/05/2021`]} // "MM/DD/YYYY"
...
/>
```

**Comment by koladei** [comment]
Thanks @edwardfxiao ,

It worked nicely.
