### ISSUE TITLE
React 17.0.2 and react-picky-date-time

### ISSUE THREAD

**Issue by atompie** [edwardfxiao/react-picky-date-time#14]
Hi. Thanks for the great component. 

I Have a question. When I install the component along with react 17 I have this warning. Will react-picky-date-time work with react 17?
```
warning " > react-picky-date-time@1.8.0" has incorrect peer dependency "react@^16.8.6".
warning " > react-picky-date-time@1.8.0" has incorrect peer dependency "react-dom@^16.8.6".
```

The component also requires `react-addons-css-transition-group@15.6.2` which further depends on

```
react-addons-css-transition-group@15.6.2" has incorrect peer dependency "react@^15.4.2".
```

**Comment by edwardfxiao** [comment]
@atompie Yes, I do think it works with later versions of those dependencies.

It won't be an issue because what I wrote for peer dependency is basically saying that it requires at least "react@^16.8.6". and "react@^15.4.2". it can go higher but not lower.

**Comment by atompie** [comment]
@edwardfxiao Maybe then configuring dependencies this way would not raise those warnings. As far as I undersand `react@^16.8.6` sticks to version 16.

```
react@^16.8.6 || react@^17.0.0
```

**Comment by edwardfxiao** [comment]
@atompie Do you have a better solution? Like without this ```||``` sign?

**Comment by atompie** [comment]
@edwardfxiao I guess this is the way how they solve it.

**Comment by edwardfxiao** [comment]
@atompie Try ```v1.8.1``` see if it has any issue

**Comment by edwardfxiao** [comment]
@atompie Try v1.8.1 see if it has any issue

**Comment by edwardfxiao** [comment]
@atompie Migrating ```react-addons-css-transition-group``` to ```react-transition-group``` needs lots of work. I gotta do it later.

**Comment by edwardfxiao** [comment]
@atompie Hi, I just released the version of 1.9.0 which upgrades to ```react-transition-group```. Please give it a try

**Comment by atompie** [comment]
@edwardfxiao Thanks I will do that :) Thanks.

**Comment by edwardfxiao** [comment]
@atompie One more thing, in previous versions I forgot to remove ```react-addons-update```, which really does nothing. I took it out in v1.9.1

**Comment by atompie** [comment]
Thanks.
